hw7_2: simple_int_set.o simple_int_set_main.o
	g++ -o simple_int_set simple_int_set.o simple_int_set_main.o
simple_int_set.o: simple_int_set.cpp
	g++ -c simple_int_set.cpp
simple_int_set_main.o: simple_int_set_main.cpp
	g++ -c simple_int_set_main.cpp
clean:
	rm simple_int_set.o simple_int_set_main.o

