
hw2_1: array_pointer.o call_by_reference.o
	g++ -o array_pointer array_pointer.o
	g++ -o call_by_reference call_by_reference.o
array_pointer.o: array_pointer.cpp
	g++ -c array_pointer.cpp
call_by_reference.o: call_by_reference.cpp
	g++ -c call_by_reference.cpp
clean:
	rm  array_pointer.o call_by_reference.o .call_by_reference.swp

