hw2_3: min_max_sum.o rotate_integer.o
	g++ -o min_max_sum min_max_sum.o
	g++ -o rotate_integer rotate_integer.o
min_max_sum.o: min_max_sum.cpp
	g++ -c min_max_sum.cpp
rotate_integer.o: rotate_integer.cpp
	g++ -c rotate_integer.cpp
clean:
	rm min_max_sum.o rotate_integer.o 

