hw4_2: print_people.o my_list.o
	g++ -o print_people print_people.o
	g++ -o my_list my_list.o
print_people.o: print_people.cpp
	g++ -c print_people.cpp
my_list.o: my_list.cpp
	g++ -c my_list.cpp
clean:
	rm print_people.o my_list.o
