
hw6-3: minimal_fighter_main.o minimal_fighter.o
	g++ -o minimal_fighter minimal_fighter_main.o minimal_fighter.o
minimal_fighter_main.o: minimal_fighter_main.cpp
	g++ -c minimal_fighter_main.cpp
minimal_fighter.o: minimal_fighter.cpp
	g++ -c minimal_fighter.cpp
clean:
	rm minimal_fighter minimal_fighter_main.o minimal_fighter.o
