
hw2_2: get_sum_diff.o to_lower_upper.o
	g++ -o get_sum_diff get_sum_diff.o
	g++ -o to_lower_upper to_lower_upper.o
get_sum_diff.o: get_sum_diff.cpp
	g++ -c get_sum_diff.cpp
to_lower_upper.o: to_lower_upper.cpp
	g++ -c to_lower_upper.cpp
clean:
	rm get_sum_diff.o to_lower_upper.o 
