hw8_2:draw_shape.o draw_shape_main.o
	g++ -o draw_shape draw_shape.o draw_shape_main.o
draw_shape.o:draw_shape.cpp
	g++ -c draw_shape.cpp
draw_shape_main.o:draw_shape_main.cpp
	g++ -c draw_shape_main.cpp
clean:
	rm draw_shape.o draw_shape_main.o
