
hw3_2: array_struct_point.o score_graph.o print_point.o
	g++ -o array_struct_point array_struct_point.o
	g++ -o score_graph score_graph.o
	g++ -o print_point print_point.o
array_struct_point.o: array_struct_point.cpp
	g++ -c array_struct_point.cpp
score_graph.o: score_graph.cpp
	g++ -c score_graph.cpp
print_point.o: print_point.cpp
	g++ -c print_point.cpp
clean: 
	rm array_struct_point.o score_graph.o print_point.o
